name: TPTrace
main: io.github.soulofakuma
version: 1.0.0
commands:
  back:
    description: Go back to the position you were previously teleported from.
    usage: /back [number of steps]
    permission: local.dec.TPTrace.back
    permission-message: You don't have the permission to run this command